package com.migration.validator.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Model classes for code-metadata.yaml structure.
 * These classes map to the YAML structure generated by CLDK extractors.
 *
 * All classes are public static to allow YAML deserialization while keeping
 * them in one file.
 */
public class PersistenceModels {

    // ============================================================================
    // Field Model
    // ============================================================================
    public static class FieldModel {
        private String name;
        private String type;
        private Boolean nullable;
        private Boolean unique;
        private String column;
        private List<String> annotations = new ArrayList<>();
        @JsonProperty("transient")
        private boolean transientField;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public Boolean getNullable() {
            return nullable;
        }

        public void setNullable(Boolean nullable) {
            this.nullable = nullable;
        }

        public Boolean getUnique() {
            return unique;
        }

        public void setUnique(Boolean unique) {
            this.unique = unique;
        }

        public String getColumn() {
            return column;
        }

        public void setColumn(String column) {
            this.column = column;
        }

        public List<String> getAnnotations() {
            return annotations;
        }

        public void setAnnotations(List<String> annotations) {
            this.annotations = annotations;
        }

        public boolean isTransientField() {
            return transientField;
        }

        public void setTransientField(boolean transientField) {
            this.transientField = transientField;
        }
    }

    // ============================================================================
    // Relationship Model
    // Field order matches Python Relationship dataclass:
    // type, collection_type, target_entity, mapped_by, fetch, cascade, column
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "type", "collection_type", "target_entity", "mapped_by", "fetch", "cascade", "column"
    })
    public static class RelationshipModel {
        private String type; // OneToMany, ManyToOne, OneToOne, ManyToMany
        @JsonProperty("collection_type")
        private String collectionType;
        @JsonProperty("target_entity")
        private String targetEntity;
        @JsonProperty("mapped_by")
        private String mappedBy;
        private String fetch;
        private List<String> cascade;
        private String column;

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getCollectionType() {
            return collectionType;
        }

        public void setCollectionType(String collectionType) {
            this.collectionType = collectionType;
        }

        public String getTargetEntity() {
            return targetEntity;
        }

        public void setTargetEntity(String targetEntity) {
            this.targetEntity = targetEntity;
        }

        public String getMappedBy() {
            return mappedBy;
        }

        public void setMappedBy(String mappedBy) {
            this.mappedBy = mappedBy;
        }

        public String getFetch() {
            return fetch;
        }

        public void setFetch(String fetch) {
            this.fetch = fetch;
        }

        public List<String> getCascade() {
            return cascade;
        }

        public void setCascade(List<String> cascade) {
            this.cascade = cascade;
        }

        public String getColumn() {
            return column;
        }

        public void setColumn(String column) {
            this.column = column;
        }
    }

    // ============================================================================
    // ID Generation Model
    // ============================================================================
    public static class IdGenerationModel {
        private String strategy;
        private String generator;

        public String getStrategy() {
            return strategy;
        }

        public void setStrategy(String strategy) {
            this.strategy = strategy;
        }

        public String getGenerator() {
            return generator;
        }

        public void setGenerator(String generator) {
            this.generator = generator;
        }
    }

    // ============================================================================
    // ID Field Model
    // ============================================================================
    public static class IdFieldModel {
        private String name;
        private String type;
        private String strategy;
        private String generator;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getStrategy() {
            return strategy;
        }

        public void setStrategy(String strategy) {
            this.strategy = strategy;
        }

        public String getGenerator() {
            return generator;
        }

        public void setGenerator(String generator) {
            this.generator = generator;
        }
    }

    // ============================================================================
    // Named Query Model
    // Field order matches Python NamedQueryModel: name, query, type, is_modifying,
    // parameters
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "name", "query", "type", "is_modifying", "parameters"
    })
    public static class NamedQueryModel {
        private String name;
        private String query;
        private String type;
        @JsonProperty("is_modifying")
        private boolean isModifying;
        private List<String> parameters = new ArrayList<>();

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getQuery() {
            return query;
        }

        public void setQuery(String query) {
            this.query = query;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public List<String> getParameters() {
            return parameters;
        }

        public void setParameters(List<String> parameters) {
            this.parameters = parameters;
        }

        @com.fasterxml.jackson.annotation.JsonIgnore
        public boolean isModifying() {
            return isModifying;
        }

        public void setModifying(boolean modifying) {
            isModifying = modifying;
        }
    }

    // ============================================================================
    // Entity Field Reference (used for composite_id and version_field)
    // Matches what extractors.py actually writes: {"name": ..., "type": ...}
    // ============================================================================
    public static class EntityFieldRef {
        private String name;
        private String type;

        public EntityFieldRef() {
        }

        public EntityFieldRef(String name, String type) {
            this.name = name;
            this.type = type;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }
    }

    // ============================================================================
    // Transaction-related models (mirrors Python TransactionManagement hierarchy)
    // ============================================================================
    public static class UserTransactionInfo {
        @JsonProperty("field_name")
        private String fieldName;
        @JsonProperty("field_type")
        private String fieldType;
        @JsonProperty("resource_injected")
        private boolean resourceInjected;
        private boolean detected;

        public String getFieldName() {
            return fieldName;
        }

        public void setFieldName(String fieldName) {
            this.fieldName = fieldName;
        }

        public String getFieldType() {
            return fieldType;
        }

        public void setFieldType(String fieldType) {
            this.fieldType = fieldType;
        }

        public boolean isResourceInjected() {
            return resourceInjected;
        }

        public void setResourceInjected(boolean resourceInjected) {
            this.resourceInjected = resourceInjected;
        }

        public boolean isDetected() {
            return detected;
        }

        public void setDetected(boolean detected) {
            this.detected = detected;
        }
    }

    public static class ManualTransactionCall {
        private String method;
        private List<String> operations = new ArrayList<>();
        private String signature;

        public String getMethod() {
            return method;
        }

        public void setMethod(String method) {
            this.method = method;
        }

        public List<String> getOperations() {
            return operations;
        }

        public void setOperations(List<String> operations) {
            this.operations = operations;
        }

        public String getSignature() {
            return signature;
        }

        public void setSignature(String signature) {
            this.signature = signature;
        }
    }

    public static class TransactionAttribute {
        private String method;
        private String propagation;
        private String attribute;
        private String annotation;

        public String getMethod() {
            return method;
        }

        public void setMethod(String method) {
            this.method = method;
        }

        public String getPropagation() {
            return propagation;
        }

        public void setPropagation(String propagation) {
            this.propagation = propagation;
        }

        @com.fasterxml.jackson.annotation.JsonIgnore
        public String getAttribute() {
            return attribute;
        }

        public void setAttribute(String attribute) {
            this.attribute = attribute;
        }

        public String getAnnotation() {
            return annotation;
        }

        public void setAnnotation(String annotation) {
            this.annotation = annotation;
        }
    }

    public static class TransactionManagementModel {
        private String type;
        @JsonProperty("user_transaction")
        private UserTransactionInfo userTransaction;
        @JsonProperty("has_manual_transactions")
        private boolean hasManualTransactions;
        @JsonProperty("manual_transaction_calls")
        private List<ManualTransactionCall> manualTransactionCalls = new ArrayList<>();
        @JsonProperty("transaction_attributes")
        private List<TransactionAttribute> transactionAttributes = new ArrayList<>();

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public UserTransactionInfo getUserTransaction() {
            return userTransaction;
        }

        public void setUserTransaction(UserTransactionInfo userTransaction) {
            this.userTransaction = userTransaction;
        }

        public boolean isHasManualTransactions() {
            return hasManualTransactions;
        }

        public void setHasManualTransactions(boolean hasManualTransactions) {
            this.hasManualTransactions = hasManualTransactions;
        }

        public List<ManualTransactionCall> getManualTransactionCalls() {
            return manualTransactionCalls;
        }

        public void setManualTransactionCalls(List<ManualTransactionCall> manualTransactionCalls) {
            this.manualTransactionCalls = manualTransactionCalls;
        }

        public List<TransactionAttribute> getTransactionAttributes() {
            return transactionAttributes;
        }

        public void setTransactionAttributes(List<TransactionAttribute> transactionAttributes) {
            this.transactionAttributes = transactionAttributes;
        }
    }

    // ============================================================================
    // Entity Model
    // Field order matches Python dataclass EntityModel field declaration order:
    // original_file, package_name, class_name, extends, implements, table_name,
    // indexes, id_field, id_generation, composite_id, inheritance_strategy,
    // version_field, named_queries, relationships, fields, soft_delete_flag,
    // annotations
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "original_file", "package_name", "class_name", "extends", "implements",
            "table_name", "indexes", "id_field", "id_generation", "composite_id",
            "inheritance_strategy", "version_field", "named_queries", "relationships",
            "fields", "soft_delete_flag", "annotations"
    })
    public static class EntityModel {
        @JsonProperty("original_file")
        private String originalFile;
        @JsonProperty("package_name")
        private String packageName;
        @JsonProperty("class_name")
        private String className;
        @JsonProperty("extends")
        private List<String> extendsClasses = new ArrayList<>();
        @JsonProperty("implements")
        private List<String> implementsInterfaces = new ArrayList<>();
        @JsonProperty("table_name")
        private String tableName;
        private List<Map<String, String>> indexes = new ArrayList<>();
        @JsonProperty("id_field")
        private IdFieldModel idField;
        @JsonProperty("id_generation")
        private IdGenerationModel idGeneration;
        @JsonProperty("composite_id")
        private EntityFieldRef compositeId;
        @JsonProperty("inheritance_strategy")
        private String inheritanceStrategy;
        @JsonProperty("version_field")
        private EntityFieldRef versionField;
        @JsonProperty("named_queries")
        private List<NamedQueryModel> namedQueries = new ArrayList<>();
        private List<RelationshipModel> relationships = new ArrayList<>();
        private List<FieldModel> fields = new ArrayList<>();
        @JsonProperty("soft_delete_flag")
        private boolean softDeleteFlag;
        private List<String> annotations = new ArrayList<>();

        public String getOriginalFile() {
            return originalFile;
        }

        public void setOriginalFile(String originalFile) {
            this.originalFile = originalFile;
        }

        public String getPackageName() {
            return packageName;
        }

        public void setPackageName(String packageName) {
            this.packageName = packageName;
        }

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public List<String> getExtendsClasses() {
            return extendsClasses;
        }

        public void setExtendsClasses(List<String> extendsClasses) {
            this.extendsClasses = extendsClasses;
        }

        public List<String> getImplementsInterfaces() {
            return implementsInterfaces;
        }

        public void setImplementsInterfaces(List<String> implementsInterfaces) {
            this.implementsInterfaces = implementsInterfaces;
        }

        public String getTableName() {
            return tableName;
        }

        public void setTableName(String tableName) {
            this.tableName = tableName;
        }

        public List<Map<String, String>> getIndexes() {
            return indexes;
        }

        public void setIndexes(List<Map<String, String>> indexes) {
            this.indexes = indexes;
        }

        public IdFieldModel getIdField() {
            return idField;
        }

        public void setIdField(IdFieldModel idField) {
            this.idField = idField;
        }

        public IdGenerationModel getIdGeneration() {
            return idGeneration;
        }

        public void setIdGeneration(IdGenerationModel idGeneration) {
            this.idGeneration = idGeneration;
        }

        public EntityFieldRef getCompositeId() {
            return compositeId;
        }

        public void setCompositeId(EntityFieldRef compositeId) {
            this.compositeId = compositeId;
        }

        public String getInheritanceStrategy() {
            return inheritanceStrategy;
        }

        public void setInheritanceStrategy(String inheritanceStrategy) {
            this.inheritanceStrategy = inheritanceStrategy;
        }

        public EntityFieldRef getVersionField() {
            return versionField;
        }

        public void setVersionField(EntityFieldRef versionField) {
            this.versionField = versionField;
        }

        public List<NamedQueryModel> getNamedQueries() {
            return namedQueries;
        }

        public void setNamedQueries(List<NamedQueryModel> namedQueries) {
            this.namedQueries = namedQueries;
        }

        public List<RelationshipModel> getRelationships() {
            return relationships;
        }

        public void setRelationships(List<RelationshipModel> relationships) {
            this.relationships = relationships;
        }

        public List<FieldModel> getFields() {
            return fields;
        }

        public void setFields(List<FieldModel> fields) {
            this.fields = fields;
        }

        public boolean isSoftDeleteFlag() {
            return softDeleteFlag;
        }

        public void setSoftDeleteFlag(boolean softDeleteFlag) {
            this.softDeleteFlag = softDeleteFlag;
        }

        public List<String> getAnnotations() {
            return annotations;
        }

        public void setAnnotations(List<String> annotations) {
            this.annotations = annotations;
        }
    }

    // ============================================================================
    // Repository Model
    // Spring repos output: original_file, package_name, class_name,
    // uses_entity_manager, autowired_dependencies, transaction_management,
    // managed_entities, entity_operations, operations
    // Jakarta repos output adds: ejb_type, persistence_context,
    // persistence_unit
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "original_file", "package_name", "class_name", "ejb_type",
            "uses_entity_manager", "persistence_context", "persistence_unit",
            "autowired_dependencies", "transaction_management",
            "managed_entities", "entity_operations", "operations"
    })
    public static class RepositoryModel {
        @JsonProperty("original_file")
        private String originalFile;
        @JsonProperty("package_name")
        private String packageName;
        @JsonProperty("class_name")
        private String className;
        @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
        @JsonProperty("ejb_type")
        private String ejbType;
        @JsonProperty("uses_entity_manager")
        private boolean usesEntityManager;
        @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
        @JsonProperty("persistence_context")
        private Boolean persistenceContext;
        @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
        @JsonProperty("persistence_unit")
        private Boolean persistenceUnit;
        @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
        @JsonProperty("autowired_dependencies")
        private List<java.util.Map<String, Object>> autowiredDependencies;
        @JsonProperty("transaction_management")
        private TransactionManagementModel transactionManagement;
        @JsonProperty("managed_entities")
        private List<String> managedEntities = new ArrayList<>();
        @JsonProperty("entity_operations")
        private Map<String, List<String>> entityOperations = new java.util.LinkedHashMap<>();
        private List<String> operations = new ArrayList<>();

        public String getOriginalFile() {
            return originalFile;
        }

        public void setOriginalFile(String originalFile) {
            this.originalFile = originalFile;
        }

        public String getPackageName() {
            return packageName;
        }

        public void setPackageName(String packageName) {
            this.packageName = packageName;
        }

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public String getEjbType() {
            return ejbType;
        }

        public void setEjbType(String ejbType) {
            this.ejbType = ejbType;
        }

        public boolean isUsesEntityManager() {
            return usesEntityManager;
        }

        public void setUsesEntityManager(boolean usesEntityManager) {
            this.usesEntityManager = usesEntityManager;
        }

        public Boolean isPersistenceContext() {
            return persistenceContext;
        }

        public void setPersistenceContext(Boolean persistenceContext) {
            this.persistenceContext = persistenceContext;
        }

        public Boolean isPersistenceUnit() {
            return persistenceUnit;
        }

        public void setPersistenceUnit(Boolean persistenceUnit) {
            this.persistenceUnit = persistenceUnit;
        }

        public List<java.util.Map<String, Object>> getAutowiredDependencies() {
            return autowiredDependencies;
        }

        public void setAutowiredDependencies(List<java.util.Map<String, Object>> autowiredDependencies) {
            this.autowiredDependencies = autowiredDependencies;
        }

        public TransactionManagementModel getTransactionManagement() {
            return transactionManagement;
        }

        public void setTransactionManagement(TransactionManagementModel transactionManagement) {
            this.transactionManagement = transactionManagement;
        }

        public List<String> getManagedEntities() {
            return managedEntities;
        }

        public void setManagedEntities(List<String> managedEntities) {
            this.managedEntities = managedEntities;
        }

        public Map<String, List<String>> getEntityOperations() {
            return entityOperations;
        }

        public void setEntityOperations(Map<String, List<String>> entityOperations) {
            this.entityOperations = entityOperations;
        }

        public List<String> getOperations() {
            return operations;
        }

        public void setOperations(List<String> operations) {
            this.operations = operations;
        }
    }

    // ============================================================================
    // DataSource Usage Model
    // ============================================================================
    public static class DataSourceUsageModel {
        @JsonProperty("original_file")
        private String originalFile;
        @JsonProperty("package_name")
        private String packageName;
        @JsonProperty("class_name")
        private String className;
        @JsonProperty("field_name")
        private String fieldName;
        @JsonProperty("uses_resource")
        private boolean usesResource;
        @JsonProperty("uses_inject")
        private boolean usesInject;
        @JsonProperty("uses_autowired")
        private boolean usesAutowired;
        @JsonProperty("jndi_name")
        private String jndiName;

        public String getOriginalFile() {
            return originalFile;
        }

        public void setOriginalFile(String originalFile) {
            this.originalFile = originalFile;
        }

        public String getPackageName() {
            return packageName;
        }

        public void setPackageName(String packageName) {
            this.packageName = packageName;
        }

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public String getFieldName() {
            return fieldName;
        }

        public void setFieldName(String fieldName) {
            this.fieldName = fieldName;
        }

        public boolean isUsesResource() {
            return usesResource;
        }

        public void setUsesResource(boolean usesResource) {
            this.usesResource = usesResource;
        }

        public boolean isUsesInject() {
            return usesInject;
        }

        public void setUsesInject(boolean usesInject) {
            this.usesInject = usesInject;
        }

        public boolean isUsesAutowired() {
            return usesAutowired;
        }

        public void setUsesAutowired(boolean usesAutowired) {
            this.usesAutowired = usesAutowired;
        }

        public String getJndiName() {
            return jndiName;
        }

        public void setJndiName(String jndiName) {
            this.jndiName = jndiName;
        }
    }

    // ============================================================================
    // EntityManager Usage Model
    // ============================================================================
    public static class EntityManagerUsageModel {
        @JsonProperty("original_file")
        private String originalFile;
        @JsonProperty("package_name")
        private String packageName;
        @JsonProperty("class_name")
        private String className;
        @JsonProperty("field_name")
        private String fieldName;
        @JsonProperty("uses_persistence_context")
        private boolean usesPersistenceContext;
        @JsonProperty("uses_inject")
        private boolean usesInject;
        @JsonProperty("unit_name")
        private String unitName;

        public String getOriginalFile() {
            return originalFile;
        }

        public void setOriginalFile(String originalFile) {
            this.originalFile = originalFile;
        }

        public String getPackageName() {
            return packageName;
        }

        public void setPackageName(String packageName) {
            this.packageName = packageName;
        }

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public String getFieldName() {
            return fieldName;
        }

        public void setFieldName(String fieldName) {
            this.fieldName = fieldName;
        }

        public boolean isUsesPersistenceContext() {
            return usesPersistenceContext;
        }

        public void setUsesPersistenceContext(boolean usesPersistenceContext) {
            this.usesPersistenceContext = usesPersistenceContext;
        }

        public boolean isUsesInject() {
            return usesInject;
        }

        public void setUsesInject(boolean usesInject) {
            this.usesInject = usesInject;
        }

        public String getUnitName() {
            return unitName;
        }

        public void setUnitName(String unitName) {
            this.unitName = unitName;
        }
    }

    // ============================================================================
    // Dependency Info Model
    // Python DependencyInfo field order: group_id, artifact_id, version
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({ "group_id", "artifact_id", "version" })
    public static class DependencyInfoModel {
        @JsonProperty("group_id")
        private String groupId;
        @JsonProperty("artifact_id")
        private String artifactId;
        private String version;

        public DependencyInfoModel() {
        }

        public DependencyInfoModel(String groupId, String artifactId, String version) {
            this.groupId = groupId;
            this.artifactId = artifactId;
            this.version = version;
        }

        public String getGroupId() {
            return groupId;
        }

        public void setGroupId(String groupId) {
            this.groupId = groupId;
        }

        public String getArtifactId() {
            return artifactId;
        }

        public void setArtifactId(String artifactId) {
            this.artifactId = artifactId;
        }

        public String getVersion() {
            return version;
        }

        public void setVersion(String version) {
            this.version = version;
        }
    }

    // ============================================================================
    // Server Datasource Model (mirrors Python DataSourceConfig /
    // models.DataSourceConfig)
    // ============================================================================
    public static class ServerDatasourceModel {
        @JsonProperty("jdbc_url")
        private String jdbcUrl;
        @JsonProperty("driver_class")
        private String driverClass;
        @JsonProperty("driver_type")
        private String driverType;

        public ServerDatasourceModel() {
        }

        public ServerDatasourceModel(String jdbcUrl, String driverClass, String driverType) {
            this.jdbcUrl = jdbcUrl;
            this.driverClass = driverClass;
            this.driverType = driverType;
        }

        public String getJdbcUrl() {
            return jdbcUrl;
        }

        public void setJdbcUrl(String jdbcUrl) {
            this.jdbcUrl = jdbcUrl;
        }

        public String getDriverClass() {
            return driverClass;
        }

        public void setDriverClass(String driverClass) {
            this.driverClass = driverClass;
        }

        public String getDriverType() {
            return driverType;
        }

        public void setDriverType(String driverType) {
            this.driverType = driverType;
        }
    }

    // ============================================================================
    // Persistence Property Model
    // ============================================================================
    public static class PersistenceProperty {
        private String key;
        private String value;

        public String getKey() {
            return key;
        }

        public void setKey(String key) {
            this.key = key;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }
    }

    // ============================================================================
    // Persistence Config Model
    // Python PersistenceConfig field order: persistence_xml_exists, properties,
    // then rest
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "persistence_xml_exists", "properties", "datasource_url", "datasource_driver",
            "datasource_username", "hibernate_dialect", "hibernate_ddl_auto",
            "hibernate_show_sql", "jta_data_source", "transaction_type"
    })
    public static class PersistenceConfigModel {
        @JsonProperty("persistence_xml_exists")
        private boolean persistenceXmlExists;
        private List<PersistenceProperty> properties = new ArrayList<>();
        @JsonProperty("datasource_url")
        private String datasourceUrl;
        @JsonProperty("datasource_driver")
        private String datasourceDriver;
        @JsonProperty("datasource_username")
        private String datasourceUsername;
        @JsonProperty("hibernate_dialect")
        private String hibernateDialect;
        @JsonProperty("hibernate_ddl_auto")
        private String hibernateDdlAuto;
        @JsonProperty("hibernate_show_sql")
        private Boolean hibernateShowSql;
        @JsonProperty("jta_data_source")
        private String jtaDataSource;
        @JsonProperty("transaction_type")
        private String transactionType;

        public boolean isPersistenceXmlExists() {
            return persistenceXmlExists;
        }

        public void setPersistenceXmlExists(boolean persistenceXmlExists) {
            this.persistenceXmlExists = persistenceXmlExists;
        }

        public List<PersistenceProperty> getProperties() {
            return properties;
        }

        public void setProperties(List<PersistenceProperty> properties) {
            this.properties = properties;
        }

        public String getDatasourceUrl() {
            return datasourceUrl;
        }

        public void setDatasourceUrl(String datasourceUrl) {
            this.datasourceUrl = datasourceUrl;
        }

        public String getDatasourceDriver() {
            return datasourceDriver;
        }

        public void setDatasourceDriver(String datasourceDriver) {
            this.datasourceDriver = datasourceDriver;
        }

        public String getDatasourceUsername() {
            return datasourceUsername;
        }

        public void setDatasourceUsername(String datasourceUsername) {
            this.datasourceUsername = datasourceUsername;
        }

        public String getHibernateDialect() {
            return hibernateDialect;
        }

        public void setHibernateDialect(String hibernateDialect) {
            this.hibernateDialect = hibernateDialect;
        }

        public String getHibernateDdlAuto() {
            return hibernateDdlAuto;
        }

        public void setHibernateDdlAuto(String hibernateDdlAuto) {
            this.hibernateDdlAuto = hibernateDdlAuto;
        }

        public Boolean getHibernateShowSql() {
            return hibernateShowSql;
        }

        public void setHibernateShowSql(Boolean hibernateShowSql) {
            this.hibernateShowSql = hibernateShowSql;
        }

        public String getJtaDataSource() {
            return jtaDataSource;
        }

        public void setJtaDataSource(String jtaDataSource) {
            this.jtaDataSource = jtaDataSource;
        }

        public String getTransactionType() {
            return transactionType;
        }

        public void setTransactionType(String transactionType) {
            this.transactionType = transactionType;
        }
    }

    // ============================================================================
    // Project Config Model
    // ============================================================================
    public static class ProjectConfigModel {
        private List<DependencyInfoModel> dependencies = new ArrayList<>();
        @JsonProperty("persistence_config")
        private PersistenceConfigModel persistenceConfig;
        @JsonProperty("javax_persistence_import_files")
        private List<String> javaxPersistenceImportFiles = new ArrayList<>();
        @JsonProperty("server_datasources")
        private List<ServerDatasourceModel> serverDatasources = new ArrayList<>();

        public List<DependencyInfoModel> getDependencies() {
            return dependencies;
        }

        public void setDependencies(List<DependencyInfoModel> dependencies) {
            this.dependencies = dependencies;
        }

        public PersistenceConfigModel getPersistenceConfig() {
            return persistenceConfig;
        }

        public void setPersistenceConfig(PersistenceConfigModel persistenceConfig) {
            this.persistenceConfig = persistenceConfig;
        }

        public List<String> getJavaxPersistenceImportFiles() {
            return javaxPersistenceImportFiles;
        }

        public void setJavaxPersistenceImportFiles(List<String> javaxPersistenceImportFiles) {
            this.javaxPersistenceImportFiles = javaxPersistenceImportFiles;
        }

        public List<ServerDatasourceModel> getServerDatasources() {
            return serverDatasources;
        }

        public void setServerDatasources(List<ServerDatasourceModel> serverDatasources) {
            this.serverDatasources = serverDatasources;
        }
    }

    // ============================================================================
    // Root Repo Metadata Model
    // Python RepoModel field order: entities, repositories, rest, servlets,
    // exception_mappers, project_config, datasource_usages, entity_manager_usages
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "entities", "repositories", "rest", "servlets", "exception_mappers",
            "project_config", "datasource_usages", "entity_manager_usages"
    })
    public static class RepoMetadataModel {
        private List<EntityModel> entities = new ArrayList<>();
        private List<RepositoryModel> repositories = new ArrayList<>();
        private RestModels.RestModel rest;
        private List<RestModels.ServletModel> servlets = new ArrayList<>();
        @JsonProperty("exception_mappers")
        private List<RestModels.ExceptionMapperModel> exceptionMappers = new ArrayList<>();
        @JsonProperty("project_config")
        private ProjectConfigModel projectConfig;
        @JsonProperty("datasource_usages")
        private List<DataSourceUsageModel> datasourceUsages = new ArrayList<>();
        @JsonProperty("entity_manager_usages")
        private List<EntityManagerUsageModel> entityManagerUsages = new ArrayList<>();

        public List<EntityModel> getEntities() {
            return entities;
        }

        public void setEntities(List<EntityModel> entities) {
            this.entities = entities;
        }

        public List<RepositoryModel> getRepositories() {
            return repositories;
        }

        public void setRepositories(List<RepositoryModel> repositories) {
            this.repositories = repositories;
        }

        public RestModels.RestModel getRest() {
            return rest;
        }

        public void setRest(RestModels.RestModel rest) {
            this.rest = rest;
        }

        public List<RestModels.ServletModel> getServlets() {
            return servlets;
        }

        public void setServlets(List<RestModels.ServletModel> servlets) {
            this.servlets = servlets;
        }

        public List<RestModels.ExceptionMapperModel> getExceptionMappers() {
            return exceptionMappers;
        }

        public void setExceptionMappers(List<RestModels.ExceptionMapperModel> exceptionMappers) {
            this.exceptionMappers = exceptionMappers;
        }

        public List<DataSourceUsageModel> getDatasourceUsages() {
            return datasourceUsages;
        }

        public void setDatasourceUsages(List<DataSourceUsageModel> datasourceUsages) {
            this.datasourceUsages = datasourceUsages;
        }

        public List<EntityManagerUsageModel> getEntityManagerUsages() {
            return entityManagerUsages;
        }

        public void setEntityManagerUsages(List<EntityManagerUsageModel> entityManagerUsages) {
            this.entityManagerUsages = entityManagerUsages;
        }

        public ProjectConfigModel getProjectConfig() {
            return projectConfig;
        }

        public void setProjectConfig(ProjectConfigModel projectConfig) {
            this.projectConfig = projectConfig;
        }
    }
}
