package com.migration.validator.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Model classes for REST API metadata structure.
 * These classes map to the YAML structure generated by CLDK extractors.
 */
public class RestModels {

    // ============================================================================
    // REST Parameter Model
    // ============================================================================
    public static class RestParameter {
        private String name;
        private String type;
        @JsonProperty("maps_to")
        private String mapsTo;
        @JsonProperty("default_value")
        private String defaultValue;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getMapsTo() {
            return mapsTo;
        }

        public void setMapsTo(String mapsTo) {
            this.mapsTo = mapsTo;
        }

        public String getDefaultValue() {
            return defaultValue;
        }

        public void setDefaultValue(String defaultValue) {
            this.defaultValue = defaultValue;
        }
    }

    // ============================================================================
    // REST Operation Model
    // Python RestOperation order: method, subpath, request_type, response_type,
    // security,
    // consumes, produces, annotations, path_params, query_params, form_params
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "method", "subpath", "request_type", "response_type", "security",
            "consumes", "produces", "annotations", "path_params", "query_params", "form_params"
    })
    public static class RestOperation {
        private String method;
        private String subpath;
        @JsonProperty("path_params")
        private List<RestParameter> pathParams = new ArrayList<>();
        @JsonProperty("query_params")
        private List<RestParameter> queryParams = new ArrayList<>();
        @JsonProperty("form_params")
        private List<RestParameter> formParams = new ArrayList<>();
        @JsonProperty("request_type")
        private String requestType;
        @JsonProperty("response_type")
        private String responseType;
        private Object security;
        private List<String> consumes = new ArrayList<>();
        private List<String> produces = new ArrayList<>();
        private List<String> annotations = new ArrayList<>();

        public String getMethod() {
            return method;
        }

        public void setMethod(String method) {
            this.method = method;
        }

        public String getSubpath() {
            return subpath;
        }

        public void setSubpath(String subpath) {
            this.subpath = subpath;
        }

        public List<RestParameter> getPathParams() {
            return pathParams;
        }

        public void setPathParams(List<RestParameter> pathParams) {
            this.pathParams = pathParams;
        }

        public List<RestParameter> getQueryParams() {
            return queryParams;
        }

        public void setQueryParams(List<RestParameter> queryParams) {
            this.queryParams = queryParams;
        }

        public List<RestParameter> getFormParams() {
            return formParams;
        }

        public void setFormParams(List<RestParameter> formParams) {
            this.formParams = formParams;
        }

        public String getRequestType() {
            return requestType;
        }

        public void setRequestType(String requestType) {
            this.requestType = requestType;
        }

        public String getResponseType() {
            return responseType;
        }

        public void setResponseType(String responseType) {
            this.responseType = responseType;
        }

        public Object getSecurity() {
            return security;
        }

        public void setSecurity(Object security) {
            this.security = security;
        }

        public List<String> getConsumes() {
            return consumes;
        }

        public void setConsumes(List<String> consumes) {
            this.consumes = consumes;
        }

        public List<String> getProduces() {
            return produces;
        }

        public void setProduces(List<String> produces) {
            this.produces = produces;
        }

        public List<String> getAnnotations() {
            return annotations;
        }

        public void setAnnotations(List<String> annotations) {
            this.annotations = annotations;
        }
    }

    // ============================================================================
    // REST API Model
    // Python RestResource order: path, file, class_name, annotations,
    // injected_dependencies, context_injections, consumes, produces, operations
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({
            "path", "file", "class_name", "annotations", "injected_dependencies",
            "context_injections", "consumes", "produces", "operations"
    })
    public static class RestApi {
        private String path;
        private String file;
        @JsonProperty("class_name")
        private String className;
        private List<String> annotations = new ArrayList<>();
        @JsonProperty("injected_dependencies")
        private List<Object> injectedDependencies = new ArrayList<>();
        @JsonProperty("context_injections")
        private List<Object> contextInjections = new ArrayList<>();
        private List<String> consumes = new ArrayList<>();
        private List<String> produces = new ArrayList<>();
        private List<RestOperation> operations = new ArrayList<>();

        public String getPath() {
            return path;
        }

        public void setPath(String path) {
            this.path = path;
        }

        public String getFile() {
            return file;
        }

        public void setFile(String file) {
            this.file = file;
        }

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public List<String> getAnnotations() {
            return annotations;
        }

        public void setAnnotations(List<String> annotations) {
            this.annotations = annotations;
        }

        public List<Object> getInjectedDependencies() {
            return injectedDependencies;
        }

        public void setInjectedDependencies(List<Object> injectedDependencies) {
            this.injectedDependencies = injectedDependencies;
        }

        public List<Object> getContextInjections() {
            return contextInjections;
        }

        public void setContextInjections(List<Object> contextInjections) {
            this.contextInjections = contextInjections;
        }

        public List<String> getConsumes() {
            return consumes;
        }

        public void setConsumes(List<String> consumes) {
            this.consumes = consumes;
        }

        public List<String> getProduces() {
            return produces;
        }

        public void setProduces(List<String> produces) {
            this.produces = produces;
        }

        public List<RestOperation> getOperations() {
            return operations;
        }

        public void setOperations(List<RestOperation> operations) {
            this.operations = operations;
        }
    }

    // ============================================================================
    // REST Model (Root)
    // Python RestModel order: root_path, apis
    // ============================================================================
    @com.fasterxml.jackson.annotation.JsonPropertyOrder({ "root_path", "apis" })
    public static class RestModel {
        @JsonProperty("root_path")
        private String rootPath;
        private List<RestApi> apis = new ArrayList<>();

        public String getRootPath() {
            return rootPath;
        }

        public void setRootPath(String rootPath) {
            this.rootPath = rootPath;
        }

        public List<RestApi> getApis() {
            return apis;
        }

        public void setApis(List<RestApi> apis) {
            this.apis = apis;
        }
    }

    // ============================================================================
    // Exception Mapper Model
    // ============================================================================
    public static class ExceptionMapperModel {
        @JsonProperty("class_name")
        private String className;
        private String file;
        @JsonProperty("exception_type")
        private String exceptionType;

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public String getFile() {
            return file;
        }

        public void setFile(String file) {
            this.file = file;
        }

        public String getExceptionType() {
            return exceptionType;
        }

        public void setExceptionType(String exceptionType) {
            this.exceptionType = exceptionType;
        }
    }

    // ============================================================================
    // Servlet Model
    // ============================================================================
    public static class ServletModel {
        @JsonProperty("class_name")
        private String className;
        private String file;
        @JsonProperty("url_patterns")
        private List<String> urlPatterns = new ArrayList<>();
        @JsonProperty("http_methods")
        private List<String> httpMethods = new ArrayList<>();
        private List<String> annotations = new ArrayList<>();

        public String getClassName() {
            return className;
        }

        public void setClassName(String className) {
            this.className = className;
        }

        public String getFile() {
            return file;
        }

        public void setFile(String file) {
            this.file = file;
        }

        public List<String> getUrlPatterns() {
            return urlPatterns;
        }

        public void setUrlPatterns(List<String> urlPatterns) {
            this.urlPatterns = urlPatterns;
        }

        public List<String> getHttpMethods() {
            return httpMethods;
        }

        public void setHttpMethods(List<String> httpMethods) {
            this.httpMethods = httpMethods;
        }

        public List<String> getAnnotations() {
            return annotations;
        }

        public void setAnnotations(List<String> annotations) {
            this.annotations = annotations;
        }
    }

    // ============================================================================
    // Root Metadata Model (contains rest section)
    // ============================================================================
    public static class CodeMetadata {
        private RestModel rest;
        // Other sections can be added as needed

        public RestModel getRest() {
            return rest;
        }

        public void setRest(RestModel rest) {
            this.rest = rest;
        }
    }
}
